<template>
  <svg class="flowchart" viewBox="0 0 560 200" role="img"
    aria-label="Data-flow: every frame the CPU selects the visible chunks at constant cost; each new chunk's surface is generated by a GPU compute shader or a CPU worker pool; the GPU always realizes the geometry, bakes the atlas, and renders. Chunks are cached and built once.">
    <defs>
      <marker id="gen-ah-gpu" markerWidth="7" markerHeight="7" refX="5.5" refY="3" orient="auto">
        <path class="mk-gpu" d="M0 0 L6 3 L0 6 Z" />
      </marker>
      <marker id="gen-ah-cpu" markerWidth="7" markerHeight="7" refX="5.5" refY="3" orient="auto">
        <path class="mk-cpu" d="M0 0 L6 3 L0 6 Z" />
      </marker>
    </defs>

    <!-- connectors: select -> fork -> render -->
    <path class="flow flow-gpu" marker-end="url(#gen-ah-gpu)" d="M132 86 C 166 86 172 51 202 51" />
    <path class="flow flow-cpu" marker-end="url(#gen-ah-cpu)" d="M132 106 C 166 106 172 145 202 145" />
    <path class="flow flow-gpu" marker-end="url(#gen-ah-gpu)" d="M360 51 C 386 51 388 84 406 86" />
    <path class="flow flow-cpu" marker-end="url(#gen-ah-cpu)" d="M360 145 C 386 145 388 108 406 106" />

    <!-- CPU select -->
    <rect class="node" x="12" y="62" width="120" height="66" rx="8" />
    <text class="t-title" x="72" y="86" text-anchor="middle">CPU · select</text>
    <text class="t-sub" x="72" y="101" text-anchor="middle">visible chunks</text>
    <text class="t-sub" x="72" y="114" text-anchor="middle">constant cost</text>

    <!-- GPU noise -->
    <rect class="node node-gpu" x="202" y="28" width="158" height="46" rx="8" />
    <text class="t-title t-gpu" x="281" y="48" text-anchor="middle">GPU compute</text>
    <text class="t-sub" x="281" y="62" text-anchor="middle">noise, in place</text>

    <!-- or -->
    <text class="t-mid" x="281" y="104" text-anchor="middle">or</text>

    <!-- CPU workers -->
    <rect class="node node-cpu" x="202" y="122" width="158" height="46" rx="8" />
    <text class="t-title t-cpu" x="281" y="142" text-anchor="middle">CPU workers</text>
    <text class="t-sub" x="281" y="156" text-anchor="middle">off-thread → upload</text>

    <!-- GPU render -->
    <rect class="node node-gpu" x="406" y="62" width="142" height="66" rx="8" />
    <text class="t-title" x="477" y="86" text-anchor="middle">GPU render</text>
    <text class="t-sub" x="477" y="101" text-anchor="middle">realize + bake</text>
    <text class="t-sub" x="477" y="114" text-anchor="middle">no CPU readback</text>

    <!-- footer -->
    <text class="t-mid" x="280" y="190" text-anchor="middle">cached — each chunk built once, then reused</text>
  </svg>
</template>

<script setup lang="ts">
// Generation data-flow diagram for the "GPU or CPU" card.
</script>
